require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class Scraper 
	attr_reader :ids, :table, :rows, :ids
	def initialize
		@rows = []
	end

	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line|
			line =~ /state:mo/
		end.reject do |line|
			line =~ /place:/
		end.map do |line|
		  line.gsub(/,.+/, '').gsub(/\n/, '')
		end 
	end 

	def scrape_each_county_page
		i = 1	
		while i < 117 do 
			agent = Mechanize.new
			page = agent.get("http://www.sos.mo.gov/elections/goVoteMissouri/pickupmail.aspx")
			form = agent.page.forms[1]
			form.field_with(:name=>"electioncounty").options[i].click
			@table = form.submit.parser.css('#resultset').children[0]
			i += 1
			parse_county
		end
	end

	def parse_county
		if @table.children[0].text.include?("County County")
			names = @table.children[0].text.gsub!("County County", "County, County").split(",") #works for everything except Kansas and2 St Louis
			county = names[0]
			office = names[1]
		else 
			county = @table.children[0].text
		end
		phone = @table.children[6].text
		if @table.children.attribute('href').text != ""
			website = @table.children.attribute('href').text
		end
		id = @ids.find do |i|
			name = county.gsub(' County', '')
			i =~ /#{name}/i
		end || ""
		@rows << [county, office, phone, website || "", id].flatten
	end

	def write_into_CSV_file
		CSV.open("spreadsheet.csv", "wb") do |csv|
			@rows.map do |line|
				csv << line
			end
		end
	end

end

a = Scraper.new
a.get_ocd_ids
a.scrape_each_county_page
a.write_into_CSV_file
